# Projeto Spotify - Análise dos maiores sucessos do Spotify dos anos 2000 à 2019

## Instalação do Pandas e leitura da base de dados

In [204]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /home/natali/miniconda3/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/natali/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/natali/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/natali/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [205]:
df = pd.read_csv("songs_normalize.csv", index_col=False)
df.head(20)

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.30000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.01030,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.17300,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.02630,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.04080,0.001040,0.0845,0.879,172.656,pop
5,Sisqo,Thong Song,253733,True,1999,69,0.706,0.888,2,-6.959,1,0.0654,0.11900,0.000096,0.0700,0.714,121.549,"hip hop, pop, R&B"
6,Eminem,The Real Slim Shady,284200,True,2000,86,0.949,0.661,5,-4.244,0,0.0572,0.03020,0.000000,0.0454,0.760,104.504,hip hop
7,Robbie Williams,Rock DJ,258560,False,2000,68,0.708,0.772,7,-4.264,1,0.0322,0.02670,0.000000,0.4670,0.861,103.035,"pop, rock"
8,Destiny's Child,Say My Name,271333,False,1999,75,0.713,0.678,5,-3.525,0,0.1020,0.27300,0.000000,0.1490,0.734,138.009,"pop, R&B"
9,Modjo,Lady - Hear Me Tonight,307153,False,2001,77,0.720,0.808,6,-5.627,1,0.0379,0.00793,0.029300,0.0634,0.869,126.041,Dance/Electronic
10,Gigi D'Agostino,L'Amour Toujours,238759,False,2011,1,0.617,0.728,7,-7.932,1,0.0292,0.03280,0.048200,0.3600,0.808,139.066,pop
11,Eiffel 65,Move Your Body - Gabry Ponte Original Radio Edit,268863,False,1999,56,0.745,0.958,7,-9.664,1,0.0287,0.08130,0.324000,0.5330,0.960,129.962,pop
12,Bomfunk MC's,Freestyler,306333,False,2000,55,0.822,0.922,11,-5.798,0,0.0989,0.02910,0.325000,0.2520,0.568,163.826,pop
13,Sting,Desert Rose,285960,False,1999,62,0.586,0.659,0,-7.920,0,0.0304,0.01100,0.000000,0.1060,0.147,111.989,"rock, pop"
14,Melanie C,Never Be The Same Again,294200,False,1999,61,0.689,0.685,3,-5.153,1,0.0478,0.09210,0.000000,0.1190,0.398,160.067,"pop, Dance/Electronic"
15,Aaliyah,Try Again,284000,False,2002,53,0.797,0.622,6,-5.642,0,0.2900,0.08070,0.000000,0.0841,0.731,93.020,"hip hop, pop, R&B"
16,Anastacia,I'm Outta Love - Radio Edit,245400,False,1999,64,0.761,0.716,10,-5.800,0,0.0560,0.39600,0.000000,0.0771,0.649,119.410,pop
17,Alice Deejay,Better Off Alone,214883,False,2000,73,0.671,0.880,8,-6.149,0,0.0552,0.00181,0.691000,0.2850,0.782,136.953,pop
18,Gigi D'Agostino,The Riddle,285426,False,1999,64,0.740,0.876,6,-6.870,0,0.0369,0.01730,0.001520,0.0785,0.825,127.002,pop
19,Dr. Dre,The Next Episode,161506,True,1999,82,0.922,0.909,10,-2.429,0,0.2700,0.02810,0.000000,0.0856,0.309,95.295,hip hop

### Informações

##### artist = nome do artista
##### song = nome da música
##### duration_ms = duração em milissegundos
##### explicit = se a letra é explícita ou não
##### year = ano de lançamento da faixa
##### popularity = popularidade da faixa
##### danceability = o quão adequada essa música é para dançar
##### energy = medida perceptiva de intensidade e atividade
##### loudness = notação padrão de classe de altura
##### mode = modalidade melódica da faixa
##### speechiness = a característica "speechiness" (fala) detecta a presença de palavras faladas em uma faixa (usada para medir e identificar podcasts, audiobook, talk show, etc)
##### acousticness = acústica da música
##### instrumentalness = prevê se a faixa não contém vocais
##### liveness = verifica se há a presença de público na música
##### valence = uma medida que descreve a positividade musical transmitida pela faixa
##### tempo = o andamento geral estimado de uma faixa em batidas por minuto (BPM)
##### genre = gênero musical

### Verificando colunas

In [206]:
print(df.columns)

Index(['artist', 'song', 'duration_ms', 'explicit', 'year', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'genre'],
      dtype='str')

### Conversão dos milissegundos para minutos (coluna "duration_ms")

In [207]:
df['duration_mn'] = (df['duration_ms'] / 60000).round(2)
df

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mn
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop,3.52
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop",2.78
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country",4.18
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal",3.74
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop,3.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop,3.02
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop,2.97
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,1,0.1090,0.0669,0.000000,0.2740,0.811,97.984,"hip hop, country",3.34
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop,2.85
1999,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497,1,0.0395,0.1920,0.002440,0.0863,0.553,120.042,hip hop,3.59

### Análise: As músicas de qual ano são as de mais sucesso?

In [208]:
df.groupby("year")['popularity'].mean().sort_values(ascending=False)

year
2018    70.850467
1999    64.921053
2008    63.721649
2019    63.011236
2002    62.400000
2005    61.759615
2009    61.535714
2010    60.747664
2012    60.556522
2007    59.925532
2001    59.407407
2014    59.384615
2003    58.793814
2011    58.565657
2000    58.554054
2004    58.427083
2015    57.747475
2006    57.389474
2013    54.786517
2016    54.171717
2017    53.882883
1998    49.000000
2020    43.333333
Name: popularity, dtype: float64

### Análise: Qual o artista com mais músicas escutadas durante esse intervalo de anos?

In [209]:
df.groupby('artist')['popularity'].mean().sort_values(ascending=False)

artist
Tom Odell             88.0
The Neighbourhood     87.0
WILLOW                86.0
Lewis Capaldi         84.0
Gesaffelstein         84.0
                      ...
Lucenzo                0.0
Tim Berg               0.0
CNCO                   0.0
Axwell /\ Ingrosso     0.0
Azealia Banks          0.0
Name: popularity, Length: 835, dtype: float64

### Análise: Qual o artista com mais músicas escutadas durante os anos de 2015 à 2019?

In [219]:
df2015 = df[df['year'] > 2015]
df2015

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mn,filtro_anos,genre_adjusted
29,Chicane,Don't Give Up,210786,False,2016,47,0.644,0.720,10,-9.635,...,0.0419,0.00145,0.504000,0.0839,0.530,132.017,Dance/Electronic,3.51,True,Dance/Electronic
46,Samantha Mumba,Gotta Tell You,201946,False,2018,43,0.729,0.632,0,-8.750,...,0.0279,0.19100,0.000000,0.1660,0.774,109.981,pop,3.37,True,pop
154,Usher,Pop Ya Collar - Radio Edit,210813,False,2016,26,0.888,0.800,5,-3.944,...,0.0946,0.09010,0.000021,0.2290,0.866,106.957,"hip hop, pop, R&B",3.51,True,hip hop
154,Usher,Pop Ya Collar - Radio Edit,210813,False,2016,26,0.888,0.800,5,-3.944,...,0.0946,0.09010,0.000021,0.2290,0.866,106.957,"hip hop, pop, R&B",3.51,True,pop
154,Usher,Pop Ya Collar - Radio Edit,210813,False,2016,26,0.888,0.800,5,-3.944,...,0.0946,0.09010,0.000021,0.2290,0.866,106.957,"hip hop, pop, R&B",3.51,True,R&B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,...,0.1570,0.11700,0.000021,0.1050,0.564,169.994,pop,2.97,True,pop
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,...,0.1090,0.06690,0.000000,0.2740,0.811,97.984,"hip hop, country",3.34,True,hip hop
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,...,0.1090,0.06690,0.000000,0.2740,0.811,97.984,"hip hop, country",3.34,True,country
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,...,0.0656,0.45000,0.000002,0.2220,0.347,102.998,pop,2.85,True,pop
1999,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497,...,0.0395,0.19200,0.002440,0.0863,0.553,120.042,hip hop,3.59,True,hip hop

In [220]:
df2015.groupby('artist')['popularity'].mean().sort_values(ascending=False)

artist
Gesaffelstein    84.0
Sean Paul        84.0
Lewis Capaldi    84.0
Billie Eilish    82.8
Alec Benjamin    82.0
                 ...
Loud Luxury       0.0
Kungs             0.0
Martin Jensen     0.0
Tove Lo           0.0
The Lumineers     0.0
Name: popularity, Length: 241, dtype: float64

### Ajuste da coluna "genre"

In [211]:
df.drop(df[df['genre'] == 'set()'].index, inplace=True)
df['genre_adjusted'] = df['genre'].str.split(", ")

### Análise: Qual o gênero musical mais popular?

In [212]:
df = df.explode('genre_adjusted')
df['genre_adjusted'].unique()
df.groupby('genre_adjusted')['popularity'].mean().sort_values(ascending=False)

genre_adjusted
metal                67.984848
rock                 63.068376
classical            63.000000
hip hop              61.987147
easy listening       61.428571
Folk/Acoustic        60.200000
pop                  59.274342
latin                59.171875
R&B                  58.703540
jazz                 57.500000
country              56.571429
Dance/Electronic     54.982051
World/Traditional    53.800000
blues                45.500000
Name: popularity, dtype: float64

### Análise: Qual o artista com músicas mais "positivas"? (de acordo com o nível de valência)

In [213]:
df.groupby('artist')['valence'].mean().sort_values(ascending=False)

artist
Vengaboys            0.9730
Juanes               0.9730
The Roots            0.9660
Foster The People    0.9650
Silentó              0.9640
                      ...
Klingande            0.0951
Staind               0.0824
Dennis Lloyd         0.0793
Otto Knows           0.0694
Hoobastank           0.0681
Name: valence, Length: 813, dtype: float64

### Análise: Qual o artista com músicas mais "positivas" entre os anos de 2015 à 2019? (de acordo com o nível de valência)

In [221]:
df2015.groupby('artist')['valence'].mean().sort_values(ascending=False)

artist
Jonas Brothers    0.9130
Nelly             0.9070
DNCE              0.8960
Regard            0.8840
Normani           0.8810
                   ...
Rich The Kid      0.1580
Lil Peep          0.1450
Mustard           0.1370
YG                0.1120
Dennis Lloyd      0.0793
Name: valence, Length: 241, dtype: float64

### Análise: Quais as músicas ao vivo mais escutadas?

In [214]:
df.groupby(['song', 'liveness'])['popularity'].mean().sort_values(ascending=False)

song                    liveness
Sweater Weather         0.1010      89.0
Another Love            0.0944      88.0
Without Me              0.2370      87.0
Wait a Minute!          0.0943      86.0
lovely (with Khalid)    0.0950      86.0
                                    ...
Years - ラジオ・エディット       0.1740       0.0
Here                    0.0793       0.0
3005                    0.0769       0.0
#SELFIE - Original Mix  0.0818       0.0
212                     0.0767       0.0
Name: popularity, Length: 1912, dtype: float64

### Análise: Qual o ano com mais músicas "negativas" lançadas? (de acordo com o nível de valência)

In [215]:
df.groupby('year')['valence'].mean().sort_values(ascending=True)

year
2018    0.467830
2016    0.476256
2015    0.477868
2017    0.478372
2014    0.491505
2013    0.493616
2019    0.520882
1998    0.527000
2011    0.532483
2005    0.553879
2008    0.555208
1999    0.556132
2012    0.562226
2020    0.572200
2007    0.573654
2009    0.576367
2010    0.578386
2002    0.578452
2006    0.614424
2004    0.616126
2003    0.626050
2000    0.640324
2001    0.661970
Name: valence, dtype: float64

### Análise: Qual artista possui as músicas com maior medida de "Speechiness"?

In [216]:
df.groupby('artist')['speechiness'].mean().sort_values(ascending=False)

artist
MiMS                        0.5760
Lil Baby                    0.5300
Afroman                     0.4880
Russ Millions               0.4780
Polo G                      0.4670
                             ...
Lilly Wood and The Prick    0.0258
Emeli Sandé                 0.0249
All Saints                  0.0242
Ryan Cabrera                0.0241
Steps                       0.0239
Name: speechiness, Length: 813, dtype: float64

### Análise: Qual artista possui mais faixas com letras explícitas?

In [217]:
df.groupby('artist')['explicit'].count().sort_values(ascending=False)

artist
Rihanna          75
Drake            69
Calvin Harris    60
David Guetta     54
Chris Brown      51
                 ..
A1                1
A$AP Rocky        1
iio               1
t.A.T.u.          1
99 Souls          1
Name: explicit, Length: 813, dtype: int64

### Análise: Qual gênero musical possui maior taxa de dançabilidade?

In [218]:
df = df.explode('genre_adjusted')
df['genre_adjusted'].unique()
df.groupby('genre_adjusted')['danceability'].mean().sort_values(ascending=False)

genre_adjusted
latin                0.724078
hip hop              0.718072
R&B                  0.689418
pop                  0.670214
Dance/Electronic     0.666792
blues                0.649750
easy listening       0.612000
World/Traditional    0.603000
classical            0.590000
country              0.578143
Folk/Acoustic        0.567400
rock                 0.555641
jazz                 0.548000
metal                0.511061
Name: danceability, dtype: float64

### Análise: Quais foram as músicas mais escutadas de cada ano? (de 2015 à 2019)

In [222]:
df2015.groupby('song')['popularity'].mean().sort_values(ascending=False)

song
lovely (with Khalid)                          86.0
Circles                                       85.0
Perfect                                       85.0
Someone You Loved                             84.0
Shape of You                                  84.0
                                              ...
Cool Girl                                      0.0
Body (feat. brando)                            0.0
Cold (feat. Future)                            0.0
This Girl - Kungs Vs. Cookin' On 3 Burners     0.0
There's Nothing Holdin' Me Back                0.0
Name: popularity, Length: 395, dtype: float64