# Projeto Spotify - Análise dos maiores sucessos do Spotify dos anos 2000 à 2019
**Autor(a):** Natali Mendonça Dau

**Data:** 11/03/2026

**Objetivo:** Avaliar os dados das músicas de maior sucesso da plataforma Spotify entre os anos 2000 e 2019, com o propósito de limpar e analisar os dados.

---
## 1. Importação de Bibliotecas

- Instalação e importação do Pandas.

In [1]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /home/natali/miniconda3/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/natali/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/natali/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/natali/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

- Importação do Database e visualização.

In [2]:
df = pd.read_csv("songs_normalize.csv", index_col=False)

---
## 2. Carregamento dos Dados
- **Fonte dos dados:** Conjunto de dados da plataforma Kaggle
- **Dicionário de dados:** https://www.kaggle.com/datasets/paradisejoy/top-hits-spotify-from-20002019
- Verificação inicial das dimensões do conjunto de dados (linhas e colunas).

In [3]:
print(df.columns)

Index(['artist', 'song', 'duration_ms', 'explicit', 'year', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'genre'],
      dtype='str')

---
## 3. Análise Exploratória de Dados (EDA)
- **Visualização inicial:**

In [4]:
df.head(20)

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.30000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.01030,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.17300,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.02630,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.04080,0.001040,0.0845,0.879,172.656,pop
5,Sisqo,Thong Song,253733,True,1999,69,0.706,0.888,2,-6.959,1,0.0654,0.11900,0.000096,0.0700,0.714,121.549,"hip hop, pop, R&B"
6,Eminem,The Real Slim Shady,284200,True,2000,86,0.949,0.661,5,-4.244,0,0.0572,0.03020,0.000000,0.0454,0.760,104.504,hip hop
7,Robbie Williams,Rock DJ,258560,False,2000,68,0.708,0.772,7,-4.264,1,0.0322,0.02670,0.000000,0.4670,0.861,103.035,"pop, rock"
8,Destiny's Child,Say My Name,271333,False,1999,75,0.713,0.678,5,-3.525,0,0.1020,0.27300,0.000000,0.1490,0.734,138.009,"pop, R&B"
9,Modjo,Lady - Hear Me Tonight,307153,False,2001,77,0.720,0.808,6,-5.627,1,0.0379,0.00793,0.029300,0.0634,0.869,126.041,Dance/Electronic
10,Gigi D'Agostino,L'Amour Toujours,238759,False,2011,1,0.617,0.728,7,-7.932,1,0.0292,0.03280,0.048200,0.3600,0.808,139.066,pop
11,Eiffel 65,Move Your Body - Gabry Ponte Original Radio Edit,268863,False,1999,56,0.745,0.958,7,-9.664,1,0.0287,0.08130,0.324000,0.5330,0.960,129.962,pop
12,Bomfunk MC's,Freestyler,306333,False,2000,55,0.822,0.922,11,-5.798,0,0.0989,0.02910,0.325000,0.2520,0.568,163.826,pop
13,Sting,Desert Rose,285960,False,1999,62,0.586,0.659,0,-7.920,0,0.0304,0.01100,0.000000,0.1060,0.147,111.989,"rock, pop"
14,Melanie C,Never Be The Same Again,294200,False,1999,61,0.689,0.685,3,-5.153,1,0.0478,0.09210,0.000000,0.1190,0.398,160.067,"pop, Dance/Electronic"
15,Aaliyah,Try Again,284000,False,2002,53,0.797,0.622,6,-5.642,0,0.2900,0.08070,0.000000,0.0841,0.731,93.020,"hip hop, pop, R&B"
16,Anastacia,I'm Outta Love - Radio Edit,245400,False,1999,64,0.761,0.716,10,-5.800,0,0.0560,0.39600,0.000000,0.0771,0.649,119.410,pop
17,Alice Deejay,Better Off Alone,214883,False,2000,73,0.671,0.880,8,-6.149,0,0.0552,0.00181,0.691000,0.2850,0.782,136.953,pop
18,Gigi D'Agostino,The Riddle,285426,False,1999,64,0.740,0.876,6,-6.870,0,0.0369,0.01730,0.001520,0.0785,0.825,127.002,pop
19,Dr. Dre,The Next Episode,161506,True,1999,82,0.922,0.909,10,-2.429,0,0.2700,0.02810,0.000000,0.0856,0.309,95.295,hip hop

- **Estatística Descritiva:** Resumo estatístico das variáveis numéricas (média, mediana, desvio padrão) e contagem das categóricas.
- **Análise Univariada:** Distribuição individual de cada variável (histogramas, boxplots).
- **Análise Bivariada e Multivariada:** Relação entre as variáveis independentes e a variável alvo. Matriz de correlação para identificar multicolinearidade.

In [21]:
df.describe()

,duration_ms,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_mn
count,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000,3682.000000
mean,229748.678707,2009.340576,59.682238,0.671636,0.718331,5.432645,-5.510056,0.548615,0.106518,0.126379,0.014110,0.181093,0.553370,119.722659,3.829144
std,37534.624164,5.788562,21.072482,0.138792,0.151495,3.623169,1.928738,0.497699,0.095656,0.168068,0.083788,0.141583,0.219211,26.828947,0.625754
min,113000.000000,1998.000000,0.000000,0.129000,0.054900,0.000000,-20.514000,0.000000,0.023200,0.000019,0.000000,0.021500,0.038100,60.019000,1.880000
25%,205426.000000,2004.000000,56.000000,0.585000,0.619000,2.000000,-6.481000,0.000000,0.040725,0.014300,0.000000,0.087000,0.394000,98.523000,3.420000
50%,224933.000000,2010.000000,65.000000,0.680000,0.733000,6.000000,-5.292500,1.000000,0.063550,0.055600,0.000000,0.124000,0.560000,120.025000,3.750000
75%,250000.000000,2014.000000,73.000000,0.767000,0.837000,8.000000,-4.165250,1.000000,0.137000,0.176000,0.000061,0.240000,0.730000,133.040250,4.167500
max,484146.000000,2020.000000,89.000000,0.975000,0.999000,11.000000,-0.276000,1.000000,0.576000,0.976000,0.985000,0.853000,0.973000,210.851000,8.070000

---
## 4. Pré-processamento e Limpeza de Dados
- **Tratamento de Outliers:**

In [5]:
df.drop(df[df['genre'] == 'set()'].index, inplace=True)

- **Correção de Tipos de Dados:**

In [6]:
df['genre_adjusted'] = df['genre'].str.split(", ")
df = df.explode('genre_adjusted')
df['genre_adjusted'].unique()

<StringArray>
[              'pop',              'rock',           'country',
             'metal',           'hip hop',               'R&B',
  'Dance/Electronic',     'Folk/Acoustic',    'easy listening',
             'latin',             'blues', 'World/Traditional',
              'jazz',         'classical']
Length: 14, dtype: str

---
## 5. Engenharia de Atributos (Feature Engineering)
- **Criação de novas variáveis:**

In [ ]:
df2015 = df[df['year'] > 2015]

- **Escalonamento de Variáveis (Scaling/Normalization):**

In [ ]:
df['duration_mn'] = (df['duration_ms'] / 60000).round(2)

### Análise: As músicas de qual ano são as de mais sucesso?

In [8]:
df.groupby("year")['popularity'].mean().sort_values(ascending=False)

year
2018    71.730769
1999    64.584615
2008    62.763441
2019    62.145833
2002    60.847458
2010    60.611111
2009    60.594771
2005    60.262136
2011    60.215000
2007    60.152174
2012    60.106977
2003    59.521053
2001    59.078431
2006    58.930380
2004    58.902439
2014    58.718085
2015    57.462766
2000    56.904412
2017    54.726257
2013    54.687943
2016    53.055556
1998    49.000000
2020    44.200000
Name: popularity, dtype: float64

### Análise: Qual o artista com mais músicas escutadas durante esse intervalo de anos?

In [9]:
df.groupby('artist')['popularity'].mean().sort_values(ascending=False)

artist
Tom Odell                  88.0
The Neighbourhood          87.0
WILLOW                     86.0
Lewis Capaldi              84.0
Gesaffelstein              84.0
                           ...
Basement Jaxx               0.0
AlunaGeorge                 0.0
Tim Berg                    0.0
Asaf Avidan & the Mojos     0.0
Astrid S                    0.0
Name: popularity, Length: 813, dtype: float64

### Análise: Qual o artista com mais músicas escutadas durante os anos de 2015 à 2019?

In [11]:
df2015.groupby('artist')['popularity'].mean().sort_values(ascending=False)

artist
Gesaffelstein    84.0
Sean Paul        84.0
Lewis Capaldi    84.0
Billie Eilish    82.8
Alec Benjamin    82.0
                 ...
Loud Luxury       0.0
Kungs             0.0
Martin Jensen     0.0
Tove Lo           0.0
The Lumineers     0.0
Name: popularity, Length: 241, dtype: float64

### Análise: Qual o gênero musical mais popular?

In [12]:
df.groupby('genre_adjusted')['popularity'].mean().sort_values(ascending=False)

genre_adjusted
metal                67.984848
rock                 63.068376
classical            63.000000
hip hop              61.987147
easy listening       61.428571
Folk/Acoustic        60.200000
pop                  59.274342
latin                59.171875
R&B                  58.703540
jazz                 57.500000
country              56.571429
Dance/Electronic     54.982051
World/Traditional    53.800000
blues                45.500000
Name: popularity, dtype: float64

### Análise: Qual o artista com músicas mais "positivas"? (de acordo com o nível de valência)

In [13]:
df.groupby('artist')['valence'].mean().sort_values(ascending=False)

artist
Vengaboys            0.9730
Juanes               0.9730
The Roots            0.9660
Foster The People    0.9650
Silentó              0.9640
                      ...
Klingande            0.0951
Staind               0.0824
Dennis Lloyd         0.0793
Otto Knows           0.0694
Hoobastank           0.0681
Name: valence, Length: 813, dtype: float64

### Análise: Qual o artista com músicas mais "positivas" entre os anos de 2015 à 2019? (de acordo com o nível de valência)

In [14]:
df2015.groupby('artist')['valence'].mean().sort_values(ascending=False)

artist
Jonas Brothers    0.9130
Nelly             0.9070
DNCE              0.8960
Regard            0.8840
Normani           0.8810
                   ...
Rich The Kid      0.1580
Lil Peep          0.1450
Mustard           0.1370
YG                0.1120
Dennis Lloyd      0.0793
Name: valence, Length: 241, dtype: float64

### Análise: Quais as músicas ao vivo mais escutadas?

In [15]:
df.groupby(['song', 'liveness'])['popularity'].mean().sort_values(ascending=False)

song                    liveness
Sweater Weather         0.1010      89.0
Another Love            0.0944      88.0
Without Me              0.2370      87.0
Wait a Minute!          0.0943      86.0
lovely (with Khalid)    0.0950      86.0
                                    ...
Years - ラジオ・エディット       0.1740       0.0
Here                    0.0793       0.0
3005                    0.0769       0.0
#SELFIE - Original Mix  0.0818       0.0
212                     0.0767       0.0
Name: popularity, Length: 1912, dtype: float64

### Análise: Qual o ano com mais músicas "negativas" lançadas? (de acordo com o nível de valência)

In [16]:
df.groupby('year')['valence'].mean().sort_values(ascending=True)

year
2018    0.467830
2016    0.476256
2015    0.477868
2017    0.478372
2014    0.491505
2013    0.493616
2019    0.520882
1998    0.527000
2011    0.532483
2005    0.553879
2008    0.555208
1999    0.556132
2012    0.562226
2020    0.572200
2007    0.573654
2009    0.576367
2010    0.578386
2002    0.578452
2006    0.614424
2004    0.616126
2003    0.626050
2000    0.640324
2001    0.661970
Name: valence, dtype: float64

### Análise: Qual artista possui as músicas com maior medida de "Speechiness"?

In [17]:
df.groupby('artist')['speechiness'].mean().sort_values(ascending=False)

artist
MiMS                        0.5760
Lil Baby                    0.5300
Afroman                     0.4880
Russ Millions               0.4780
Polo G                      0.4670
                             ...
Lilly Wood and The Prick    0.0258
Emeli Sandé                 0.0249
All Saints                  0.0242
Ryan Cabrera                0.0241
Steps                       0.0239
Name: speechiness, Length: 813, dtype: float64

### Análise: Qual artista possui mais faixas com letras explícitas?

In [18]:
df.groupby('artist')['explicit'].count().sort_values(ascending=False)

artist
Rihanna          75
Drake            69
Calvin Harris    60
David Guetta     54
Chris Brown      51
                 ..
A1                1
A$AP Rocky        1
iio               1
t.A.T.u.          1
99 Souls          1
Name: explicit, Length: 813, dtype: int64

### Análise: Qual gênero musical possui maior taxa de dançabilidade?

In [19]:
df.groupby('genre_adjusted')['danceability'].mean().sort_values(ascending=False)

genre_adjusted
latin                0.724078
hip hop              0.718072
R&B                  0.689418
pop                  0.670214
Dance/Electronic     0.666792
blues                0.649750
easy listening       0.612000
World/Traditional    0.603000
classical            0.590000
country              0.578143
Folk/Acoustic        0.567400
rock                 0.555641
jazz                 0.548000
metal                0.511061
Name: danceability, dtype: float64

### Análise: Quais foram as músicas mais escutadas de cada ano? (de 2015 à 2019)

In [20]:
df2015.groupby('song')['popularity'].mean().sort_values(ascending=False)

song
lovely (with Khalid)                          86.0
Circles                                       85.0
Perfect                                       85.0
Someone You Loved                             84.0
Shape of You                                  84.0
                                              ...
Cool Girl                                      0.0
Body (feat. brando)                            0.0
Cold (feat. Future)                            0.0
This Girl - Kungs Vs. Cookin' On 3 Burners     0.0
There's Nothing Holdin' Me Back                0.0
Name: popularity, Length: 395, dtype: float64